CREATE SCHEMA  TRAVEL AUTHORIZATION SA;

CREATE TABLE TRAVEL.USERS (ID INT PRIMARY KEY AUTO_INCREMENT,
PROFILENAME VARCHAR(255) DEFAULT ' ',
FIRSTNAME VARCHAR(255) DEFAULT ' ',
LASTNAME VARCHAR(255) DEFAULT ' ',
EMAIL VARCHAR(255) DEFAULT ' ',)



INSERT INTO TRAVEL.USERS VALUES (1, 'Stasha', 'Stacie', 'Ray', 'stasharay@yahoo.com');
INSERT INTO TRAVEL.USERS VALUES (2, 'Bell', 'Lillie', 'Ray', 'Bellray34@gmail.com');
INSERT INTO TRAVEL.USERS VALUES (3, 'Marshy', 'Marchell', 'Turner', 'marchell.turner@gmail.com');
SELECT * FROM TRAVEL.USERS;
//add Auto_Increment to db