CREATE SCHEMA  TRAVEL AUTHORIZATION SA;

CREATE TABLE TRAVEL.USERS (ID INT PRIMARY KEY AUTO_INCREMENT,
PROFILENAME VARCHAR(255) DEFAULT ' ',
FIRSTNAME VARCHAR(255) DEFAULT ' ',
LASTNAME VARCHAR(255) DEFAULT ' ',
EMAIL VARCHAR(255) DEFAULT ' ',)



INSERT INTO TRAVEL.USERS VALUES (1, 'Stasha', 'Stacie', 'Ray', 'stasharay@yahoo.com');
INSERT INTO TRAVEL.USERS VALUES (2, 'Bell', 'Lillie', 'Ray', 'Bellray34@gmail.com');
INSERT INTO TRAVEL.USERS VALUES (3, 'Marshy', 'Marchell', 'Turner', 'marchell.turner@gmail.com');
SELECT * FROM TRAVEL.USERS;
//add Auto_Increment to db



CREATE TABLE TRAVEL.POSTS
(ID INT PRIMARY KEY AUTO_INCREMENT,
PROFILENAME VARCHAR(255) DEFAULT ' ',
TRAVELDATE DATE DEFAULT ' ',
LOCATION VARCHAR(255) DEFAULT ' ',
DESTINATION VARCHAR(255) DEFAULT ' ',
RATING INT DEFAULT ' ',
USERPOST VARCHAR(255) DEFAULT ' ',
ENTRYDATE DATE DEFAULT ' ')


INSERT INTO TRAVEL.POSTS VALUES
(1, 'STASHA',
(TO_DATE('07/01/2018', 'MM/DD/YYYY')), 'ARUBA', 'HILTON', 5, 'HAD A GREAT TIME. THE STAFF WAS INCREDIBLE',
(TO_DATE('01/04/2020', 'MM/DD/YYYY')));

INSERT INTO TRAVEL.POSTS VALUES
(2, 'BELL',
(TO_DATE('06/26/2019', 'MM/DD/YYYY')), 'FORT LAUDERDALE', 'CARNIVAL HORIZON', 3, 'THE STAFF ON CARNIVAL CRUISE HORIZON WERE POLITE, HOWEVER THE FOOD WAS TERRIBLE',
(TO_DATE('01/04/2020', 'MM/DD/YYYY')));

INSERT INTO TRAVEL.POSTS VALUES
(3, 'MARSHY',
(TO_DATE('10/26/2019', 'MM/DD/YYYY')), 'LAS VEGAS', 'LUXOR HOTEL', 4, 'WHILE THE HOTEL WAS BEAUTIFUL, THE RESTAURANT PRICES WERE TOO HIGH',
(TO_DATE('01/04/2020', 'MM/DD/YYYY')))

SELECT * FROM TRAVEL.POSTS;
